### ISSUE TITLE
Adding a booking does not work

### ISSUE THREAD

**Issue by iyioon** [AY2324S1-CS2103T-F10-1/tp#181]
<img width="1300" alt="image" src="https://github.com/AY2324S1-CS2103T-F10-1/tp/assets/94742791/f291aa7c-e1a4-4901-ac8a-dc4ee24e250e">

Inputing `add r/1 d/2023-11-01 15:34 to 2023-11-02 11:00 n/John Doe p/98765432 e/johnd@example.com rm/Requested extra Queen's sized bed` results in Please do not input JSON like content error

**Comment by RB9823** [comment]
Tested this; the issue lies in the apostrophe in "Queen's".

**Comment by iyioon** [comment]
Okay, just update the example should fix it.

**Comment by iyioon** [comment]
Okay ill work on it
