### ISSUE TITLE
Typo in unflag command message

### ISSUE THREAD

**Issue by AnnabelTing** [AY2324S1-CS2103T-F10-1/tp#199]
Shows flagged booking instead of unflagged.
<img width="960" alt="Screenshot 2023-11-03 081629" src="https://github.com/AY2324S1-CS2103T-F10-1/tp/assets/122466358/fdcdc86f-eb6f-4dfb-9a68-05e0255496df">

**Comment by RB9823** [comment]
Fixed in #242 ; The Flag/Unflag feature was removed.
